### ISSUE TITLE
Adding custom templates?

### ISSUE THREAD

**Issue by grofit** [sandorfr/gulp-swagger-generator#28]
Currently it looks like it is hardcoded to only pick up templates from the internal lib folder of this module, so is there a way to provide any additional folders or routes to custom templates?

**Comment by sandorfr** [comment]
This is actually possible but I didn't advertise it using the templatePath option. The bad news is I think it' s might broken atm and I won' t have time to look into it today.

```
gulp.task('swagger:generate', function () {
    return gulp.src('./api-swagger.json')
        .pipe(swaggerGenerator({
            clientName: 'ServiceClient',
            templateOptions: {
                module: "Sample",
                scheme: 'http',
            },
            templatePath: path.join(__dirname, "./customtemplate"),
            template: "typescript-custom",
            singleFile: true
        }))
        .pipe(rename("serviceClient.ts"))
        .pipe(gulp.dest("./src/app/services/"));
});
```

The directory structure will have to differ a bit since you'll have to put the `.hbs` and `languageOptions.json`  in the same directory.

I' m still very unsatisfied with some of the choice I did for the generation context (especially the path manipulation), so I decided to leave it as is until I got a cleaner and extensible generation context, which I can support without making breaking changes.

**Comment by grofit** [comment]
no worries, we are looking at being able to generate some typescript models and possibly custom classes for the requests (as we have our own rest service for handling calls to APIs) so if its something you are looking at fixing soon then that would be great, as you already have part of the puzzle I just want to output to be a bit more custom.

**Comment by sandorfr** [comment]
It's coming in next version, see https://github.com/geeklearningio/gl-swagger-generator/issues/6

**Comment by sandorfr** [comment]
Hi @grofit, just a follow up on your question. This is now possible. Vnext took way more time than expected to mature but It is on the right track now.

You can find more information on the freshly started Wiki https://github.com/geeklearningio/gl-swagger-generator/wiki

**Comment by grofit** [comment]
thanks will take a look next time I get a chance

**Comment by sandorfr** [comment]
This is mostly a matter of documentation now. It is being tracked here : https://github.com/geeklearningio/gl-swagger-generator/issues/6
